const {test}=require('node:test');const assert=require('node:assert/strict');
const {publicationIssues,publicSnapshot,publicationCommand}=require('../dist/catalog-publication');
const id='11111111-1111-4111-8111-111111111111';
function facts(){return {product:{id,seller_id:id,title:'Cootton tee',description:'Owner supplied cotton tee',care:'Cootton advisory',care_evidence_id:id,origin_evidence_id:id,country_id:'country',category_id:'category',brand_id:'brand',form_id:'form',form_applicable:true},dictionary:[['country','COUNTRY','VN'],['category','CATEGORY','CREWNECK_TSHIRT'],['brand','BRAND','COOTTON'],['form','FORM','BOXY'],['color','COLOR','BLACK'],['size','SIZE','S']].map(([id,kind,code])=>({id,kind,code,label:code,active:true})),fabric:[{description:'Cotton',source_id:id}],skus:[{id,code:'S-M-BLK-S',color_id:'color',size_id:'size',color:'Black',size:'S',price_source:id,price:'177000',retail_tiers:1,min_quantity:1}],chart:['BODY_LENGTH','CHEST_FLAT'].map(code=>({measurement_id:code,size_id:'size',code,label:code,value_cm:'54.00',active:true,source_id:id})),images:[{id,seller_id:id,rights_evidence_id:id,path:'/media/'+id+'/'+'a'.repeat(64)+'.webp',width:450,height:450,alt:'Actual tee'}],colors:[{color_id:'color',asset_id:id,source_id:id}],video:null,sellerActive:true};}
test('complete facts pass; missing source, inactive dictionary and missing price block publication',()=>{assert.deepEqual(publicationIssues(facts()),[]);for(const change of [f=>f.product.care='',f=>f.product.origin_evidence_id=null,f=>f.skus[0].price=null,f=>f.images[0].rights_evidence_id=null,f=>f.colors=[],f=>f.dictionary[4].active=false,f=>f.chart=[],f=>f.sellerActive=false]){const f=facts();change(f);assert.ok(publicationIssues(f).length);}});
test('public product allowlist excludes private reviewer/source fields',()=>{const f=facts();f.product.privateNote='secret';const snapshot=publicSnapshot(f,'17');assert.equal(snapshot.product.version,'17');assert.equal(snapshot.product.privateNote,undefined);assert.equal(snapshot.product.origin_evidence_id,undefined);assert.equal(snapshot.skus[0].price,'177000');});

test('snapshot guards every chart measurement and size without exposing IDs in the public chart',()=>{
 const f=facts();f.chart.forEach((c,i)=>c.measurement_id='measure-'+i);
 const s=publicSnapshot(f,'17');for(const c of f.chart){assert.ok(s.dictionaryIds.includes(c.measurement_id));assert.ok(s.dictionaryIds.includes(c.size_id));}
 assert.equal(s.chart[0].measurement_id,undefined);
});
test('activation and state guards reject without writes',async()=>{const db={query(){throw Error('unexpected write');}};delete process.env.COOTTON_PUBLICATION_ENABLED;await assert.rejects(publicationCommand(db,{lifecycle:'DRAFT'},'submit',{},id),/PUBLICATION_DISABLED/);process.env.COOTTON_PUBLICATION_ENABLED='true';await assert.rejects(publicationCommand(db,{lifecycle:'DRAFT',version:'1'},'approve',{confirmed:true,declaration:'checked'},id),/INVALID_TRANSITION/);await assert.rejects(publicationCommand(db,{lifecycle:'IN_REVIEW',version:'1'},'approve',{confirmed:false,declaration:'checked'},id),/CONFIRMATION_REQUIRED/);delete process.env.COOTTON_PUBLICATION_ENABLED;});
