'use client';
import { useEffect, useState } from 'react';
import { PRODUCT_MEDIA_LIMITS } from '@cootton/contracts';
export type MediaIntake = {
  media: {id:string;width:number;height:number;approved:boolean;position:number;alt:string}[];
  colorImages: {color_id:string;asset_id:string;width:number;height:number}[];
  video: {id:string;alt:string;width:number;height:number;duration_ms:number;byte_length:number;approved:boolean}|null;
};
type Props = {intake:MediaIntake;colors:{id:string;label:string}[];onCommand:(action:string,payload:unknown)=>Promise<void>;onPreview:(kind:'image'|'thumbnail'|'video'|'poster',asset?:string)=>Promise<{base64:string;mime:string}>};
function encoded(bytes:Uint8Array) { let binary=''; for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768)); return btoa(binary); }
export default function ProductMedia({intake,colors,onCommand,onPreview}:Props) {
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[images,setImages]=useState<Record<string,string>>({}),[poster,setPoster]=useState(''),[video,setVideo]=useState('');
  useEffect(()=>()=>{if(video)URL.revokeObjectURL(video);},[video]);
  async function run(work:()=>Promise<void>){setBusy(true);setMessage('');try{await work();}catch{setMessage('Không lưu được media. Kiểm tra file, quyền và phiên đăng nhập rồi thử lại.');}finally{setBusy(false);}}
  async function upload(form:FormData,isVideo:boolean){await run(async()=>{const f=form.get('file');const max=isVideo?PRODUCT_MEDIA_LIMITS.videoBytes:PRODUCT_MEDIA_LIMITS.imageBytes;if(!(f instanceof File)||!f.size||f.size>max){setMessage(isVideo?'Chọn MP4 đã tối ưu, tối đa 8 MiB. Không tải MOV gốc.':'Chọn ảnh JPEG, PNG hoặc WebP tối đa 3 MiB.');return;}await onCommand(isVideo?'uploadVideo':'uploadImage',{base64:encoded(new Uint8Array(await f.arrayBuffer())),alt:form.get('alt'),rights:form.get('rights')});});}
  const preview=async(kind:'image'|'thumbnail',id:string)=>run(async()=>{const data=await onPreview(kind,id);setImages(p=>({...p,[kind+id]:'data:image/webp;base64,'+data.base64}));});
  return <section aria-label="Media sản phẩm"><h3>Ảnh sản phẩm</h3><p>Tối đa 9 ảnh và thêm 1 video. Thumbnail dùng chung theo màu, không tính thành ảnh gallery mới. Lưu phần đang sửa trước khi tải media. Media chưa duyệt vẫn riêng tư.</p>
    <form action={f=>upload(f,false)}><fieldset disabled={busy||intake.media.length>=PRODUCT_MEDIA_LIMITS.images}><label>Chọn ảnh<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>Mô tả ảnh (alt)<input name="alt" required maxLength={300}/></label><label>Khai báo quyền sử dụng ảnh<textarea name="rights" required maxLength={10000}/></label><button type="submit">Tải ảnh lên bản nháp</button></fieldset></form>
    {intake.media.map(m=><article key={m.id}><p>Ảnh {m.position}: {m.alt} · {m.width}×{m.height} · {m.approved?'Đã duyệt':'Chưa duyệt'}</p><button type="button" disabled={busy} onClick={()=>preview('image',m.id)}>Xem ảnh riêng tư</button>{images['image'+m.id]&&<img src={images['image'+m.id]} alt={m.alt} width={240}/>}
      <form action={f=>run(async()=>{await onCommand('setImageColor',{assetId:m.id,colorId:f.get('color'),declaration:f.get('declaration')});})}><fieldset disabled={busy}><label>Màu của ảnh<select name="color" required defaultValue=""><option value="">Chọn màu thực tế</option>{colors.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Nguồn xác nhận ảnh đúng màu<textarea name="declaration" required maxLength={10000}/></label><button type="submit">Dùng ảnh cho các SKU cùng màu</button></fieldset></form>
    </article>)}
    <h3>Thumbnail theo màu</h3>{colors.map(c=>{const m=intake.colorImages.find(a=>a.color_id===c.id);return <div key={c.id}><p>{c.label}: {m?'Đã liên kết cho các size cùng màu':'Chưa liên kết ảnh'}</p>{m&&<><button disabled={busy} type="button" onClick={()=>preview('thumbnail',m.asset_id)}>Xem thumbnail {c.label}</button>{images['thumbnail'+m.asset_id]&&<img src={images['thumbnail'+m.asset_id]} alt={'Ảnh sản phẩm màu '+c.label} width={m.width} height={m.height}/>}</>}</div>;})}
    <h3>Video sản phẩm</h3><p>MP4 H.264, không âm thanh, tối đa 720px/30fps, 60 giây và 8 MiB. Backend kiểm tra, tối ưu và tạo poster. Video chỉ tải khi bấm phát, không tải cùng nội dung trang.</p>
    {!intake.video?<form action={f=>upload(f,true)}><fieldset disabled={busy}><label>Chọn video MP4<input type="file" name="file" accept="video/mp4" required/></label><label>Mô tả video<input name="alt" required maxLength={300}/></label><label>Khai báo quyền sử dụng video<textarea name="rights" required maxLength={10000}/></label><button type="submit">Tải và tối ưu video</button></fieldset></form>:<><p>{intake.video.alt} · {(intake.video.duration_ms/1000).toFixed(1)} giây · {(intake.video.byte_length/1048576).toFixed(2)} MiB · {intake.video.approved?'Đã duyệt':'Chưa duyệt'}</p><button type="button" disabled={busy} onClick={()=>run(async()=>{const d=await onPreview('poster');setPoster('data:image/webp;base64,'+d.base64);})}>Xem poster riêng tư</button>{poster&&!video&&<img src={poster} alt={intake.video.alt} width={240}/>}<button type="button" disabled={busy||!!video} onClick={()=>run(async()=>{const d=await onPreview('video');const binary=atob(d.base64),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));setVideo(URL.createObjectURL(new Blob([bytes],{type:'video/mp4'})));})}>Phát video riêng tư</button>{video&&<video controls playsInline preload="none" autoPlay src={video} poster={poster||undefined} width={intake.video.width} height={intake.video.height} style={{maxWidth:'100%',height:'auto'}} aria-label={intake.video.alt}/>}</>}
    <p role="status">{message}</p></section>;
}
